/*******************************************************************************
/*                 O P E N  S O U R C E  --  V I N I F E R A                  **
/*******************************************************************************
 *
 *  @project       Vinifera
 *
 *  @file          AUDIO_STREAMING.H
 *
 *  @author        CCHyper, with suggestions and additional comments added by AI
 *
 *  @license       Vinifera is free software: you can redistribute it and/or
 *                 modify it under the terms of the GNU General Public License
 *                 as published by the Free Software Foundation, either version
 *                 3 of the License, or (at your option) any later version.
 *
 *                 Vinifera is distributed in the hope that it will be
 *                 useful, but WITHOUT ANY WARRANTY; without even the implied
 *                 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *                 PURPOSE. See the GNU General Public License for more details.
 *
 *                 You should have received a copy of the GNU General Public
 *                 License along with this program.
 *                 If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#pragma once

#include "always.h"
#include "wstring.h"
#include "audio_defines.h"
#include <vector>
#include <mutex>

//#define MINIAUDIO_IMPLEMENTATION      // Not needed here as we just want header info!
#include <miniaudio/miniaudio.h>


/**
 *  An active instance of a sample.
 */
class AudioStreamingClass
{
    friend class AudioManagerClass;

    public:
        AudioStreamingClass();
        virtual ~AudioStreamingClass();

        bool Open(const std::string& name, int sampleRate, int channels, int bitsPerSample, bool isPCM = true);
        void Close();

        bool Push_Chunk(const void* data, size_t size); // Raw PCM or AUD depending on isPCM

        bool Play();
        bool Pause();
        bool Stop();

        bool Is_Playing() const;
        uint64_t Get_Frames_Played() const;
        uint64_t Get_Cursor_In_PCM_Frames() const;
        ma_uint32 Get_Available_Read_Frames() const;

        AudioHandleID Get_Handle() const { return HandleID; }

    private:
        bool Initialize_PCM_Stream();
        bool Initialize_AUD_Decoder(const void * initialData, size_t size);

    private:
        /**
         *  Pointer to the Miniaudio engine sound object
         */
        ma_sound * Sound;

        /**
         *  Holds the optional decoder for streaming the WS AUD format
         */
        ma_decoder * Decoder;
        bool DecoderInitialized;
        bool DecoderIsOwnedBySound;

        /**
         *  Unique identifier generated by the audio manager, do not set manually!
         */
        AudioHandleID HandleID;

        bool StreamInitialized;

        bool IsStreaming;

        bool IsPCM; // True if raw PCM, false if AUD compressed
        ma_pcm_rb * PCMBuffer;

        std::string LogicalName;

        int SampleRate;
        int Channels;
        int BitsPerSample;

        uint64_t FramesPushed;

        // Optional: Ring buffer or chunk buffer
        std::vector<uint8_t> ChunkBuffer;

    private:
        // Disable copy semantics
        AudioStreamingClass(const AudioStreamingClass & other);
        AudioStreamingClass & operator = (const AudioStreamingClass &) = delete;
};
