/*******************************************************************************
/*                 O P E N  S O U R C E  --  V I N I F E R A                  **
/*******************************************************************************
 *  @brief  Audio sample instance class.
 *
 *  SPDX-License-Identifier: GPL-3.0-or-later
 *  Copyright (c) 2020-2026 Vinifera contributors
 ******************************************************************************/

#pragma once

#include "audio_defines.h"
#include "audio_sample.h"


struct ma_sound;
struct ma_decoder;
typedef ma_sound ma_sound_group;
class AudioSampleClass;


/**
 *  An active instance of a sample.
 */
class AudioInstanceClass
{
    friend class AudioManagerClass;

public:
    AudioInstanceClass(AudioSampleClass* tmpl, AudioInstanceHandle id);
    ~AudioInstanceClass();

    std::string Get_FileName() const { return Is_Valid() ? Template->Get_FileName() : "<unknown>"; }
    AudioInstanceHandle Get_ID() const { return HandleID; }
    AudioSampleClass const& Get_Sample_Template() const { return *Template; }

    bool Is_Ready_To_Play() const { return CurrentState == AudioHandleState::AUDIO_STATE_READY; }

    bool Is_Playing() const;
    bool Is_Paused() const { return CurrentState == AudioHandleState::AUDIO_STATE_PAUSED; }

    bool Is_Fading_Out() const;
    bool Is_Fading_In() const;

    bool Is_Looping() const;

    bool Is_Finished() const;

    bool Is_Valid() const;

    bool Play();
    bool End();

    bool Pause();
    bool Resume();
    bool Restart();

    bool Update(float deltaTime);

    bool Seek(float time);

    float Get_Volume() const;
    float Get_Pitch() const;
    float Get_Pan() const;
    float Get_Time() const;
    float Get_Length() const;
    // float Get_Delay() const;

    bool Set_Looping(bool loop);
    bool Set_Loop_Limit(int total_plays);
    bool Set_Fade(float seconds, bool out, bool end_after_out = true);
    bool Set_Volume(float volume);
    bool Set_Pitch(float pitch);
    bool Set_Pan(float pan);
    bool Set_Time(float time_in_seconds);
    bool Set_Delay(float delay_in_seconds);

    unsigned Get_Sample_Rate() const;
    unsigned Get_Channels() const;

    // bool Assign_To_Group(ma_sound_group *group) const;

    bool Is_Using_Custom_Decoder() const { return DecoderInitialized && Decoder != nullptr; }

    bool Set_User_Data(void* user_data);

private:
    bool Load();
    bool Free();

private:
    /**
     *  Pointer to the Miniaudio engine sound object
     */
    ma_sound* Sound = nullptr;

    /**
     *  Holds the optional decoder for streaming the WS AUD format
     */
    ma_decoder* Decoder = nullptr;
    bool DecoderInitialized = false;
    bool DecoderIsOwnedBySound = false;

    /**
     *  Back-reference to template
     */
    AudioSampleClass* Template = nullptr;

    /**
     *  Unique identifier generated by the audio manager, do not set manually!
     */
    AudioInstanceHandle HandleID = INVALID_AUDIO_INSTANCE_HANDLE;

    /**
     *  Current lifecycle state.
     */
    AudioHandleState CurrentState = AudioHandleState::AUDIO_STATE_NEW;

    /**
     *  Volume at fade start.
     */
    float FadeStartVolume = 1.0f;

    /**
     *  Time since fade started.
     */
    float FadeTime = 0.0f;

    /**
     *  How long the fade lasts.
     */
    float FadeDuration = 0.0f;

    bool IsLooping = false;

    /**
     *  Remaining automatic replays after the current pass completes.
     */
    int RemainingLoopRepeats = 0;

    /**
     *  Indicates if audio was loaded correctly.
     */
    bool IsLoaded = false;

    /**
     *  Whether a start delay is pending.
     */
    bool IsDelaySet = false;

public:
    // Disable copy semantics
    AudioInstanceClass(const AudioInstanceClass&) = delete;
    AudioInstanceClass& operator=(const AudioInstanceClass&) = delete;
};
